GRID_FILES_DIRECTORY= r"C:\Users\mri17\OneDrive\Documents\Stocks\MEIC_METF\Option_data_sets"
MAX_SPREAD_WIDTH=50
MIN_SPREAD_WIDTH=20
MAX_NET_CREDIT=2.80
MIN_NET_CREDIT=0.80
OPTIMAL_NET_CREDIT=1.80
# MIN_SPX_DISTANCE=10
MIN_SPX_DISTANCE=1
MIN_LONG_VAL=0.10
MAX_LONG_VAL=1.00

MAX_SHORT=2.80
MIN_SHORT=0.85

# strategies for picking best optimal spread
STRATEGY_OPTIMAL_NET_CREDIT = 0
STRATEGY_SHORT_200_LONG_010 = 1  # B Rushing strategy

PICKER_STRATEGY=STRATEGY_OPTIMAL_NET_CREDIT
PICKER_STRATEGY_DESC="STRATEGY_OPTIMAL_NET_CREDIT"

# PICKER_STRATEGY=STRATEGY_SHORT_200_LONG_010
# PICKER_STRATEGY_DESC="STRATEGY_SHORT_200_LONG_010"